# Generated by Django 4.2.3 on 2023-08-22 17:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
        migrations.AlterField(
            model_name='post',
            name='text_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
