# Generated by Django 4.2.3 on 2023-08-13 14:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maps', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Maps',
            new_name='Map',
        ),
        migrations.RenameModel(
            old_name='Markers',
            new_name='Marker',
        ),
    ]
