# Generated by Django 4.2.3 on 2023-08-15 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_rename_maps_map_rename_markers_marker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='lat',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='marker',
            name='lng',
            field=models.CharField(max_length=6),
        ),
    ]
